// @vitest-environment node
/**
 * Coverage guard: every key and every literal-union value of every AI Skill
 * output type (packages/ai-skills/src/<skill>/contracts.ts, via the TypeScript
 * type checker) has a PT-BR label. A new output field without a label would be
 * rendered as the generic "Detalhe" — this test fails first.
 */
import { describe, expect, it } from "vitest";
import * as fs from "fs";
import * as path from "path";
import ts from "typescript";
import {
  SKILL_OUTPUT_FIELD_LABELS_PT_BR,
  SKILL_OUTPUT_VALUE_LABELS_PT_BR,
  UNKNOWN_FIELD_LABEL,
  skillFieldLabel,
  skillValueLabel,
} from "./skill-output-labels.pt-br";

const SKILLS_ROOT = path.resolve(__dirname, "../../../../../packages/ai-skills/src");

function collectOutputContract(): { keys: Set<string>; values: Map<string, Set<string>> } {
  const files = fs
    .readdirSync(SKILLS_ROOT)
    .map((dir) => path.join(SKILLS_ROOT, dir, "contracts.ts"))
    .filter((file) => fs.existsSync(file));
  const program = ts.createProgram(files, { strict: true, target: ts.ScriptTarget.ES2020 });
  const checker = program.getTypeChecker();
  const keys = new Set<string>();
  const values = new Map<string, Set<string>>();
  const addValue = (owner: string | null, value: string) => {
    if (!owner) return;
    if (!values.has(owner)) values.set(owner, new Set());
    values.get(owner)!.add(value);
  };
  const walk = (type: ts.Type, owner: string | null, depth: number, seen: Set<ts.Type>): void => {
    if (depth > 6 || seen.has(type)) return;
    const next = new Set(seen).add(type);
    if (type.isUnion()) {
      for (const member of type.types) {
        if (member.isStringLiteral()) addValue(owner, member.value);
        else walk(member, owner, depth, next);
      }
      return;
    }
    if (type.isStringLiteral()) return addValue(owner, type.value);
    if (checker.isArrayType(type)) return walk(checker.getTypeArguments(type as ts.TypeReference)[0], owner, depth + 1, next);
    if (type.flags & ts.TypeFlags.Object) {
      for (const prop of checker.getPropertiesOfType(type)) {
        const decl = prop.valueDeclaration ?? prop.declarations?.[0];
        if (!decl) continue;
        keys.add(prop.name);
        walk(checker.getTypeOfSymbolAtLocation(prop, decl), prop.name, depth + 1, next);
      }
    }
  };
  let outputs = 0;
  for (const file of files) {
    const source = program.getSourceFile(file)!;
    ts.forEachChild(source, (node) => {
      if ((ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node)) && /Output$/.test(node.name.text)) {
        outputs += 1;
        walk(checker.getTypeAtLocation(node.name), null, 0, new Set());
      }
    });
  }
  expect(outputs).toBeGreaterThan(20);
  return { keys, values };
}

describe("AI Skill output labels", () => {
  const contract = collectOutputContract();

  it("labels every output key declared by the skill contracts", () => {
    const missing = [...contract.keys].filter((key) => !(key in SKILL_OUTPUT_FIELD_LABELS_PT_BR));
    expect(missing).toEqual([]);
  });

  it("labels every literal-union value declared by the skill contracts", () => {
    const missing: string[] = [];
    for (const [field, literals] of contract.values) {
      for (const literal of literals) {
        if (!SKILL_OUTPUT_VALUE_LABELS_PT_BR[field]?.[literal]) missing.push(`${field}=${literal}`);
      }
    }
    expect(missing).toEqual([]);
  });

  it("never renders the technical key or enum value", () => {
    expect(skillFieldLabel("creativeSummary")).toBe("Resumo criativo");
    expect(skillFieldLabel("SLARecommendation")).toBe("Recomendação de SLA");
    expect(skillFieldLabel("someFutureKey")).toBe(UNKNOWN_FIELD_LABEL);
    expect(skillValueLabel("severity", "high")).toBe("Alta");
    expect(skillValueLabel("healthStatus", "insufficient_data")).toBe("Dados insuficientes");
    expect(skillValueLabel("platform", "tiktok")).toBe("TikTok");
  });

  it("renders booleans and numbers in PT-BR", () => {
    expect(skillValueLabel("isDraft", true)).toBe("Sim");
    expect(skillValueLabel("escalationNeeded", false)).toBe("Não");
    expect(skillValueLabel("coveragePercentage", 1234.5)).toBe("1.234,5");
  });

  it("keeps free text generated by the model unchanged", () => {
    expect(skillValueLabel("summary", "Campanha com bom engajamento.")).toBe("Campanha com bom engajamento.");
  });
});
