/**
 * PT-BR labels for AI Skill outputs rendered by SkillRunPanel.
 *
 * Skill outputs are typed objects (packages/ai-skills/src/<skill>/contracts.ts) whose
 * KEYS are technical English identifiers and whose literal-union VALUES are
 * technical enums. Neither may reach the user: this module is the single place
 * that turns them into Brazilian Portuguese. skill-output-labels.test.ts derives
 * every output key and literal value from the contracts and fails when one is
 * missing here.
 */

export const SKILL_OUTPUT_FIELD_LABELS_PT_BR: Readonly<Record<string, string>> = {
  CTAs: "Chamadas para ação",
  SLARecommendation: "Recomendação de SLA",
  accountingNotes: "Observações contábeis",
  action: "Ação",
  adjustmentTriggers: "Gatilhos de ajuste",
  affectedModule: "Módulo afetado",
  analysisSummary: "Resumo da análise",
  area: "Área",
  asset: "Material",
  assets: "Materiais",
  audience: "Público",
  audienceAnalysis: "Análise de público",
  auditSummary: "Resumo da auditoria",
  availability: "Disponibilidade",
  blocker: "Impedimento",
  blockers: "Impedimentos",
  brandNarrative: "Narrativa de marca",
  budgetNotes: "Observações de orçamento",
  businessEvent: "Evento de negócio",
  calendar: "Calendário",
  campaignPhases: "Fases da campanha",
  captionVariants: "Variações de legenda",
  category: "Categoria",
  change: "Alteração",
  channel: "Canal",
  channelChecklist: "Checklist do canal",
  channels: "Canais",
  check: "Verificação",
  checklist: "Checklist",
  checks: "Verificações",
  competitivePositioning: "Posicionamento competitivo",
  completed: "Concluído",
  completedStepsCount: "Etapas concluídas",
  composers: "Compositores",
  concern: "Ponto de atenção",
  concerns: "Pontos de atenção",
  confidence: "Confiança",
  contentPillars: "Pilares de conteúdo",
  contentType: "Tipo de conteúdo",
  conversionProbability: "Probabilidade de conversão",
  costCenter: "Centro de custo",
  coveragePercentage: "Cobertura (%)",
  coverageSummary: "Resumo da cobertura",
  creativeConcept: "Conceito criativo",
  creativeSummary: "Resumo criativo",
  criticalIssues: "Problemas críticos",
  cta: "Chamada para ação",
  currentStage: "Etapa atual",
  dailyActions: "Ações diárias",
  dataGaps: "Lacunas de dados",
  date: "Data",
  deadlineSuggestion: "Prazo sugerido",
  deliverables: "Entregáveis",
  department: "Departamento",
  dependencies: "Dependências",
  description: "Descrição",
  draftBody: "Rascunho do texto",
  draftTitle: "Rascunho do título",
  dueInDays: "Prazo (dias)",
  duplicateRisks: "Riscos de duplicidade",
  duration: "Duração",
  endDate: "Data de término",
  entityName: "Registro",
  entityType: "Tipo de registro",
  errors: "Erros",
  escalationNeeded: "Escalonamento necessário",
  estimatedDays: "Dias estimados",
  evidence: "Evidência",
  examples: "Exemplos",
  executionSummary: "Resumo da execução",
  expenses: "Despesas",
  field: "Campo",
  finding: "Constatação",
  findings: "Constatações",
  followUpMessage: "Mensagem de acompanhamento",
  forNextCampaignType: "Para o próximo tipo de campanha",
  format: "Formato",
  frequencySuggestion: "Frequência sugerida",
  gap: "Lacuna",
  gaps: "Lacunas",
  hasMeasuredPerformanceData: "Há dados de desempenho medidos",
  hasMinimumMetadata: "Metadados mínimos presentes",
  hashtags: "Hashtags",
  headline: "Título",
  healthStatus: "Situação",
  healthSummary: "Resumo da situação",
  highlight: "Destaque",
  highlights: "Destaques",
  impact: "Impacto",
  internalNotes: "Observações internas",
  isDraft: "Rascunho",
  isValid: "Válido",
  isrc: "ISRC",
  issue: "Problema",
  item: "Item",
  keyMessages: "Mensagens-chave",
  keyObservations: "Observações principais",
  label: "Rótulo",
  lesson: "Aprendizado",
  lessonsLearned: "Aprendizados",
  likelyCause: "Causa provável",
  linkedEntitySuggestion: "Vínculo sugerido",
  location: "Local",
  matchedFields: "Campos correspondentes",
  message: "Mensagem",
  metadataReview: "Revisão de metadados",
  metric: "Métrica",
  metricProvenance: "Origem da métrica",
  metricSummaries: "Resumo das métricas",
  metricsToWatch: "Métricas a acompanhar",
  milestone: "Marco",
  milestones: "Marcos",
  missingFields: "Campos ausentes",
  missingItems: "Itens pendentes",
  missingMetadata: "Metadados ausentes",
  mitigation: "Mitigação",
  month: "Mês",
  monthlyBreakdown: "Detalhamento mensal",
  name: "Nome",
  netResult: "Resultado líquido",
  nextAction: "Próxima ação",
  nextRecommendedStep: "Próxima etapa recomendada",
  normalizedMetadata: "Metadados normalizados",
  notes: "Observações",
  objection: "Objeção",
  objections: "Objeções",
  objective: "Objetivo",
  observation: "Observação",
  onboardingSummary: "Resumo do onboarding",
  opportunities: "Oportunidades",
  opportunity: "Oportunidade",
  order: "Ordem",
  ownerArea: "Área responsável",
  percentage: "Percentual",
  percentageShare: "Participação (%)",
  performers: "Intérpretes",
  periodSummary: "Resumo do período",
  phases: "Fases",
  pillar: "Pilar",
  pipelineSummary: "Resumo do funil",
  placement: "Posicionamento do anúncio",
  placementRecommendations: "Recomendações de posicionamento",
  planSummary: "Resumo do plano",
  platform: "Plataforma",
  platformNotes: "Observações da plataforma",
  platformRecommendations: "Recomendações por plataforma",
  platformSplit: "Divisão por plataforma",
  platformStrategy: "Estratégia por plataforma",
  point: "Ponto",
  positioning: "Posicionamento",
  primaryCopy: "Texto principal",
  priority: "Prioridade",
  producers: "Produtores",
  productionChecklist: "Checklist de produção",
  productionNeeds: "Necessidades de produção",
  progressSummary: "Resumo do progresso",
  publisher: "Editora",
  rationale: "Justificativa",
  readinessScore: "Pontuação de prontidão",
  readinessSummary: "Resumo da prontidão",
  readyToRequestPublish: "Pronto para solicitar publicação",
  reason: "Motivo",
  recommendation: "Recomendação",
  recommendations: "Recomendações",
  recommendedActions: "Ações recomendadas",
  recommendedFix: "Correção recomendada",
  recommendedFixes: "Correções recomendadas",
  recurrence: "Recorrência",
  required: "Obrigatório",
  requiredAssets: "Materiais necessários",
  resolutionTime: "Tempo de resolução",
  response: "Resposta",
  responseStrategy: "Estratégia de resposta",
  responseTime: "Tempo de resposta",
  responsibility: "Responsabilidade",
  result: "Resultado",
  revenue: "Receita",
  rightsRisks: "Riscos de direitos",
  risk: "Risco",
  riskFactors: "Fatores de risco",
  risks: "Riscos",
  role: "Função",
  scene: "Cena",
  scenes: "Cenas",
  score: "Pontuação",
  script: "Roteiro",
  severity: "Gravidade",
  share: "Participação",
  shares: "Participações",
  signal: "Sinal",
  source: "Origem",
  stageRecommendation: "Etapa recomendada",
  startDate: "Data de início",
  status: "Status",
  strategicDirection: "Direção estratégica",
  strategicNarrative: "Narrativa estratégica",
  strategy: "Estratégia",
  strategySummary: "Resumo da estratégia",
  strength: "Ponto forte",
  strengths: "Pontos fortes",
  subject: "Assunto",
  successSignals: "Sinais de sucesso",
  suggestedBudgetSharePercent: "Parcela sugerida do orçamento (%)",
  suggestedDate: "Data sugerida",
  suggestedDeadline: "Prazo sugerido",
  suggestedEscalationChanges: "Ajustes de escalonamento sugeridos",
  suggestedMenuChanges: "Ajustes de menu sugeridos",
  suggestedOwners: "Responsáveis sugeridos",
  suggestedResponse: "Resposta sugerida",
  suggestedStage: "Etapa sugerida",
  suggestedTags: "Etiquetas sugeridas",
  suggestedTasks: "Tarefas sugeridas",
  suggestionsSummary: "Resumo das sugestões",
  summary: "Resumo",
  targetAudience: "Público-alvo",
  task: "Tarefa",
  tasks: "Tarefas",
  teamNeeds: "Necessidades da equipe",
  timing: "Momento",
  title: "Título",
  tone: "Tom",
  toneNotes: "Observações de tom",
  totalStepsCount: "Total de etapas",
  trend: "Tendência",
  type: "Tipo",
  unavailableMetrics: "Métricas indisponíveis",
  upc: "UPC",
  usedFacts: "Fatos utilizados",
  variant: "Variação",
  variants: "Variações",
  visualStyle: "Estilo visual",
  warnings: "Alertas",
  weaknesses: "Pontos fracos",
  why: "Motivo",
};

export const SKILL_OUTPUT_VALUE_LABELS_PT_BR: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  availability: {
    actual: "Real",
    estimated: "Estimada",
    projected: "Projetada",
    unavailable: "Indisponível",
  },
  currentStage: {
    contacted: "Contatado",
    inactive: "Inativo",
    lost: "Perdido",
    negotiation: "Em negociação",
    new: "Novo",
    proposal: "Proposta",
    qualified: "Qualificado",
    won: "Ganho",
  },
  entityType: {
    artist: "Artista",
    campaign: "Campanha",
    client: "Cliente",
    contract: "Contrato",
    none: "Nenhum",
    project: "Projeto",
    release: "Lançamento",
    supplier: "Fornecedor",
  },
  healthStatus: {
    attention: "Atenção",
    critical: "Crítica",
    healthy: "Saudável",
    insufficient_data: "Dados insuficientes",
  },
  metricProvenance: {
    actual: "Real",
    unavailable: "Indisponível",
  },
  priority: {
    critical: "Crítica",
    high: "Alta",
    low: "Baixa",
    medium: "Média",
  },
  recurrence: {
    monthly: "Mensal",
    "one-time": "Única",
    quarterly: "Trimestral",
    unknown: "Não identificada",
    weekly: "Semanal",
    yearly: "Anual",
  },
  severity: {
    critical: "Crítica",
    high: "Alta",
    info: "Informativa",
    low: "Baixa",
    medium: "Média",
  },
  source: {
    external_measurement: "Medição externa",
    static_analysis: "Análise estática",
  },
  status: {
    "almost-ready": "Quase pronto",
    "needs-attention": "Requer atenção",
    "not-ready": "Não está pronto",
    planned: "Planejado",
    ready: "Pronto",
  },
  suggestedStage: {
    contacted: "Contatado",
    inactive: "Inativo",
    lost: "Perdido",
    negotiation: "Em negociação",
    new: "Novo",
    proposal: "Proposta",
    qualified: "Qualificado",
    won: "Ganho",
  },
  trend: {
    declining: "Em queda",
    growing: "Em crescimento",
    stable: "Estável",
    volatile: "Instável",
  },
  type: {
    audio: "Áudio",
    document: "Documento",
    image: "Imagem",
    other: "Outro",
    prop: "Objeto de cena",
    recording: "Gravação",
    video: "Vídeo",
    work: "Obra",
  },
};

/** Channel/platform ids stored in lowercase become their brand names. */
const PLATFORM_NAMES: Readonly<Record<string, string>> = {
  apple_music: "Apple Music",
  deezer: "Deezer",
  email: "E-mail",
  facebook: "Facebook",
  google: "Google",
  instagram: "Instagram",
  kwai: "Kwai",
  linkedin: "LinkedIn",
  meta: "Meta",
  spotify: "Spotify",
  tiktok: "TikTok",
  twitter: "X",
  whatsapp: "WhatsApp",
  x: "X",
  youtube: "YouTube",
};

const PLATFORM_FIELDS = new Set(["platform", "channel", "channels"]);

export const UNKNOWN_FIELD_LABEL = "Detalhe";

export function skillFieldLabel(key: string): string {
  return SKILL_OUTPUT_FIELD_LABELS_PT_BR[key] ?? UNKNOWN_FIELD_LABEL;
}

/** Display value of a skill output field: enums mapped, booleans as Sim/Não, numbers in pt-BR. */
export function skillValueLabel(key: string, value: unknown): string {
  if (typeof value === "boolean") return value ? "Sim" : "Não";
  if (typeof value === "number") return value.toLocaleString("pt-BR");
  const text = String(value);
  const enumLabel = SKILL_OUTPUT_VALUE_LABELS_PT_BR[key]?.[text];
  if (enumLabel) return enumLabel;
  if (PLATFORM_FIELDS.has(key)) return PLATFORM_NAMES[text.toLowerCase()] ?? text;
  return text;
}
