import 'reflect-metadata';
import { LaunchStrategyAutomation } from './launch-strategy.automation';
import { passThroughTenantContext } from '../../../test/helpers/tenant-context.mock';

// ─── Boundary mocks (DB / SkillRunService / AIService) ────────────────────────

function makeSkillRun() {
  return {
    start: jest.fn(async () => 'run-1'),
    succeed: jest.fn(async () => undefined),
    fail: jest.fn(async () => undefined),
    log: jest.fn(async () => undefined),
  };
}

function makeAi(content: string) {
  return {
    complete: jest.fn(async () => ({
      content,
      provider: 'openai',
      model: 'gpt-4o-mini',
      inputTokens: 1,
      outputTokens: 1,
      costUsd: 0,
      latencyMs: 1,
    })),
  };
}

function makeFailingAi() {
  return { complete: jest.fn(async () => { throw new Error('No AI provider configured'); }) };
}

/**
 * DataSource mock that routes by SQL:
 *  - SELECT ... FROM skill_runs → skillRunRows
 *  - SELECT ... FROM releases   → releaseRows
 *  - UPDATE                     → undefined
 */
function makeDs(releaseRows: unknown[], skillRunRows: unknown[] = []) {
  const query = jest.fn(async (sql: string) => {
    if (/FROM\s+skill_runs/i.test(sql)) return skillRunRows;
    if (/FROM\s+releases/i.test(sql)) return releaseRows;
    return undefined;
  });
  return { ds: { query }, query };
}

function makeEvent(overrides: Record<string, unknown> = {}) {
  return {
    tenantId: 't1',
    payload: {
      releaseId: 'r1',
      tenantId: 't1',
      title: 'Verão Eterno',
      artistId: 'a1',
      approvedBy: 'u1',
      approvedAt: '2026-06-01T00:00:00.000Z',
      ...overrides,
    },
  };
}

const RELEASE_ROW = {
  title: 'Verão Eterno',
  type: 'single',
  music_genre: 'pop',
  data_lancamento: '2026-07-01T00:00:00.000Z',
  metadata: {
    aiMarketingCalendar: { parsed: { contentPillars: [{ pillar: 'Bastidores' }, { pillar: 'Lyric teasers' }] } },
  },
  artist_name: 'Banda Aurora',
};

const VALID_JSON = JSON.stringify({
  strategicNarrative: 'Uma celebração do verão através de sons nostálgicos.',
  targetAudience: 'Fãs de pop nacional, 18-24 anos',
  competitivePositioning: 'Diferenciação por autenticidade regional',
  keyMessages: [{ message: 'O verão nunca acaba', audience: 'fãs atuais' }],
  successSignals: [{ signal: 'aumento de saves em playlists', why: 'indica intenção de re-escuta' }],
  riskFactors: [{ risk: 'saturação de lançamentos de verão no mercado', severity: 'medium', mitigation: 'antecipar lançamento em 2 semanas' }],
});

const IDEMPOTENCY_KEY = 'release.approved:t1:r1';

describe('LaunchStrategyAutomation (release.approved → launch-strategy)', () => {
  it('executes, records skill_run and writes releases.metadata.aiLaunchStrategy on success', async () => {
    const { ds, query } = makeDs([RELEASE_ROW]);
    const skillRun = makeSkillRun();
    const ai = makeAi(VALID_JSON);
    const handler = new LaunchStrategyAutomation(ds as never, skillRun as never, ai as never, passThroughTenantContext(ds) as never);

    await handler.onReleaseApproved(makeEvent() as never);

    expect(skillRun.start).toHaveBeenCalledWith(
      expect.objectContaining({
        skillName: 'launch-strategy',
        entityType: 'release',
        entityId: 'r1',
        input: { idempotencyKey: IDEMPOTENCY_KEY },
      }),
    );
    expect(skillRun.succeed).toHaveBeenCalled();
    expect(skillRun.fail).not.toHaveBeenCalled();

    // reuses the real content pillars already generated by marketing-calendar-builder
    const aiCalls = ai.complete.mock.calls as unknown as Array<[{ prompt: string; jsonMode: boolean }]>;
    expect(aiCalls[0][0].jsonMode).toBe(true);
    expect(aiCalls[0][0].prompt).toContain('Verão Eterno');
    expect(aiCalls[0][0].prompt).toContain('Bastidores, Lyric teasers');
    expect(aiCalls[0][0].prompt).toContain('Banda Aurora');

    const updateCall = query.mock.calls.find((c: unknown[]) => /UPDATE\s+releases/i.test(c[0] as string));
    expect(updateCall).toBeDefined();
    const meta = JSON.parse((updateCall as unknown as [string, string[]])[1][0]);
    expect(meta.aiLaunchStrategy.source).toBe('native-automation');
    expect(meta.aiLaunchStrategy.skill).toBe('launch-strategy');
    expect(meta.aiLaunchStrategy.event).toBe('release.approved');
    expect(meta.aiLaunchStrategy.idempotencyKey).toBe(IDEMPOTENCY_KEY);
    expect(meta.aiLaunchStrategy.status).toBe('generated');
    expect(meta.aiLaunchStrategy.parsed.targetAudience).toBe('Fãs de pop nacional, 18-24 anos');
  });

  it('without a prior tactical calendar, builds input without existingCalendarSummary', async () => {
    const row = { ...RELEASE_ROW, metadata: {} };
    const { ds } = makeDs([row]);
    const skillRun = makeSkillRun();
    const ai = makeAi(VALID_JSON);
    const handler = new LaunchStrategyAutomation(ds as never, skillRun as never, ai as never, passThroughTenantContext(ds) as never);

    await handler.onReleaseApproved(makeEvent() as never);

    const aiCalls = ai.complete.mock.calls as unknown as Array<[{ prompt: string }]>;
    expect(aiCalls[0][0].prompt).not.toContain('Pilares de conteúdo');
  });

  it('metadata idempotency — does not reprocess if already generated with the same key', async () => {
    const row = { ...RELEASE_ROW, metadata: { aiLaunchStrategy: { idempotencyKey: IDEMPOTENCY_KEY, status: 'generated' } } };
    const { ds, query } = makeDs([row]);
    const skillRun = makeSkillRun();
    const ai = makeAi(VALID_JSON);
    const handler = new LaunchStrategyAutomation(ds as never, skillRun as never, ai as never, passThroughTenantContext(ds) as never);

    await handler.onReleaseApproved(makeEvent() as never);

    expect(skillRun.start).not.toHaveBeenCalled();
    expect(ai.complete).not.toHaveBeenCalled();
    expect(query.mock.calls.find((c: unknown[]) => /UPDATE/i.test(c[0] as string))).toBeUndefined();
  });

  it('skill_runs idempotency — an in-progress/successful run blocks', async () => {
    const { ds, query } = makeDs([RELEASE_ROW], [{ '1': 1 }]);
    const skillRun = makeSkillRun();
    const ai = makeAi(VALID_JSON);
    const handler = new LaunchStrategyAutomation(ds as never, skillRun as never, ai as never, passThroughTenantContext(ds) as never);

    await handler.onReleaseApproved(makeEvent() as never);

    expect(skillRun.start).not.toHaveBeenCalled();
    expect(ai.complete).not.toHaveBeenCalled();
    expect(query.mock.calls.find((c: unknown[]) => /UPDATE/i.test(c[0] as string))).toBeUndefined();
  });

  it('AI failure records fail, does not rethrow and does not write aiLaunchStrategy', async () => {
    const { ds, query } = makeDs([RELEASE_ROW]);
    const skillRun = makeSkillRun();
    const ai = makeFailingAi();
    const handler = new LaunchStrategyAutomation(ds as never, skillRun as never, ai as never, passThroughTenantContext(ds) as never);

    await expect(handler.onReleaseApproved(makeEvent() as never)).resolves.toBeUndefined();

    expect(skillRun.fail).toHaveBeenCalledWith('run-1', 't1', 'launch-strategy', expect.any(Error));
    expect(skillRun.succeed).not.toHaveBeenCalled();
    expect(query.mock.calls.find((c: unknown[]) => /UPDATE/i.test(c[0] as string))).toBeUndefined();
  });

  it('guard: missing tenantId/releaseId is ignored (no run, no query)', async () => {
    const { ds, query } = makeDs([RELEASE_ROW]);
    const skillRun = makeSkillRun();
    const ai = makeAi(VALID_JSON);
    const handler = new LaunchStrategyAutomation(ds as never, skillRun as never, ai as never, passThroughTenantContext(ds) as never);

    await handler.onReleaseApproved({ tenantId: 't1', payload: { releaseId: '' } } as never);

    expect(skillRun.start).not.toHaveBeenCalled();
    expect(query).not.toHaveBeenCalled();
  });
});
