/**
 * core/automation/postiz.automation.ts
 *
 * ON_DEMAND skill (see on-demand-skill.runner.ts): evaluates the publishing
 * readiness of a real post (`marketing_content_posts`, already generated by
 * social-content) — it NEVER publishes anything.
 *
 * Reuses the REAL, already existing connection state per channel:
 *   instagram → InstagramService.getProviderStatus (real OAuth)
 *   tiktok    → TikTokService.getOrganicStatus (real OAuth)
 *   youtube   → YouTubeService.isConfigured() (global API key, no
 *               "per-tenant connection" concept — never posting, read only)
 *   facebook/twitter/threads → no integration service exists;
 *               reported as "not_implemented" (never fabricated)
 *
 * Never calls MarketingPublishingProcessor.publish() nor any write
 * endpoint of an external provider.
 */

import { Injectable, NotFoundException } from '@nestjs/common';
import { Inject, Optional } from '@nestjs/common';
import { DataSource } from 'typeorm';
import { DATA_SOURCE } from '../../database/database.module';
import { SkillRunService } from '../skills/skill-run.service';
import { AIService } from '../../modules/ai/ai.service';
import { InstagramService } from '../../modules/integrations/instagram/instagram.service';
import { TikTokService } from '../../modules/integrations/tiktok/tiktok.service';
import { YouTubeService } from '../../modules/integrations/youtube/youtube.service';
import {
  POSTIZ_SYSTEM_PROMPT,
  buildPostizPrompt,
  parsePostizResponse,
  validatePostizInput,
  type PostizInput,
  type PostizOutput,
  type PostizChannelReadiness,
} from '@music-os-360/ai-skills';
import { runOnDemandSkill, type OnDemandSkillResult } from './on-demand-skill.runner';

const SKILL_NAME = 'postiz';

interface ContentRow {
  title: string | null;
  channel: string | null;
  copy: string | null;
}

@Injectable()
export class PostizAutomation {
  constructor(
    @Inject(DATA_SOURCE) @Optional() private readonly ds: DataSource | null,
    private readonly skillRun: SkillRunService,
    private readonly ai: AIService,
    private readonly instagram: InstagramService,
    private readonly tiktok: TikTokService,
    private readonly youtube: YouTubeService,
  ) {}

  async run(
    tenantId: string,
    userId: string,
    contentId: string,
  ): Promise<OnDemandSkillResult<PostizOutput>> {
    const row = await this.loadContent(tenantId, contentId);
    if (!row) throw new NotFoundException('Conteúdo não encontrado');

    const channel = row.channel?.trim() || 'instagram';
    const channelReadiness = await this.resolveChannelReadiness(tenantId, userId, channel);

    const input: PostizInput = {
      postTitle: row.title?.trim() || 'Post',
      channel,
      channelReadiness,
      hasCopy: !!row.copy?.trim(),
      copyLength: row.copy?.trim().length ?? 0,
      language: 'pt-BR',
    };

    return runOnDemandSkill<PostizInput, PostizOutput>(
      { skillRun: this.skillRun, ai: this.ai },
      {
        skillName: SKILL_NAME,
        tenantId,
        userId,
        entityType: 'marketing_content_post',
        entityId: contentId,
        systemPrompt: POSTIZ_SYSTEM_PROMPT,
        input,
        buildPrompt: buildPostizPrompt,
        parseResponse: parsePostizResponse,
        validateInput: validatePostizInput,
      },
    );
  }

  private async loadContent(tenantId: string, contentId: string): Promise<ContentRow | null> {
    if (!this.ds) return null;
    const rows = (await this.ds.query(
      `SELECT title, channel, copy
         FROM marketing_content_posts
        WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
        LIMIT 1`,
      [contentId, tenantId],
    )) as ContentRow[];
    return rows?.[0] ?? null;
  }

  private async resolveChannelReadiness(
    tenantId: string,
    userId: string,
    channel: string,
  ): Promise<PostizChannelReadiness> {
    try {
      if (channel === 'instagram') {
        const status = await this.instagram.getProviderStatus(tenantId, userId);
        return this.mapOAuthStatus(status);
      }
      if (channel === 'tiktok') {
        const status = await this.tiktok.getOrganicStatus(tenantId, userId);
        return this.mapOAuthStatus(status);
      }
      if (channel === 'youtube') {
        // Global API key (reading public metrics) — no concept of a
        // per-tenant connection, and no posting capability at all in the code.
        return 'not_implemented';
      }
      // facebook, twitter, threads: no integration service exists.
      return 'not_implemented';
    } catch {
      return 'provider_error';
    }
  }

  private mapOAuthStatus(status: { connected: boolean; needs_reauth?: boolean }): PostizChannelReadiness {
    if (status.needs_reauth) return 'requires_reauth';
    if (status.connected) return 'connected';
    return 'available_not_connected';
  }
}
