/**
 * integrations/mappers/transacao.mapper.ts
 *
 * Mapper between the Transaction domain entity (mockData/accounting)
 * and external DTOs (OFX import, reports, reconciliation).
 *
 * RULE: this mapper is the ONLY source of truth for the
 * Transaction ↔ external DTOs transformation. No component or hook transforms inline.
 *
 * Scope: Accounting module (revenue - expenses = net profit).
 * It does NOT cover external artist rights receipts (only the transaction category).
 *
 * Usage:
 *   import { transacaoMapper } from "@/modules/integrations/mappers";
 *   const transacao = transacaoMapper.fromOfxEntry(ofxEntry);
 */

/** Transaction domain entity (source: accounting mockData). */
export interface TransacaoEntity {
  id:          string;
  type:        "receita" | "despesa";
  categoria:   string;
  descricao:   string;
  valor:       number;
  data:        string;
  status:      "pendente" | "conciliado" | "cancelado";
  referencia?: string;
  projectId?:  string;
  artistId?:  string;
  tags?:       string[];
  createdAt:   string;
  updatedAt:   string;
}

/** OFX input line (post-parse). */
export interface OfxEntry {
  TRNTYPE:  "CREDIT" | "DEBIT" | "INT" | "DIV" | "FEE" | "SRVCHG" | "DEP";
  DTPOSTED: string; // YYYYMMDD
  TRNAMT:   number;
  FITID:    string;
  MEMO:     string;
}

export const transacaoMapper = {
  /**
   * Converts an OFX entry into a TransacaoEntity object (without id/timestamps).
   * The id and timestamps are generated by the storage layer on persistence.
   */
  fromOfxEntry(entry: OfxEntry): Omit<TransacaoEntity, "id" | "createdAt" | "updatedAt"> {
    const rawDate = entry.DTPOSTED;
    const data    = `${rawDate.slice(0, 4)}-${rawDate.slice(4, 6)}-${rawDate.slice(6, 8)}`;

    return {
      type:        entry.TRNAMT >= 0 ? "receita" : "despesa",
      categoria:   "importado",
      descricao:   entry.MEMO,
      valor:       Math.abs(entry.TRNAMT),
      data,
      status:      "pendente",
      referencia:  entry.FITID,
    };
  },

  /**
   * Computes the net balance of a list of transactions.
   * revenue - expenses = net profit (Accounting scope; no computation of external rights receipts).
   */
  calcNetProfit(transacoes: TransacaoEntity[]): number {
    return transacoes.reduce((acc, t) => {
      const signed = t.type === "receita" ? t.valor : -t.valor;
      return acc + signed;
    }, 0);
  },

  /**
   * Groups transactions by category for P&L.
   */
  groupByCategory(transacoes: TransacaoEntity[]): Record<string, TransacaoEntity[]> {
    return transacoes.reduce<Record<string, TransacaoEntity[]>>((acc, t) => {
      if (!acc[t.categoria]) acc[t.categoria] = [];
      acc[t.categoria].push(t);
      return acc;
    }, {});
  },
};
