/**
 * Part 74 — regression: GlobalExceptionFilter had an unconditional line
 * (`error = exception.name;`) executed AFTER already reading `resp['error']`
 * from the exception payload, overwriting any custom machine code
 * (e.g. `MUST_CHANGE_PASSWORD`, `TENANT_SUSPENDED`) with the generic class
 * name (`ForbiddenException`). This silently broke every guard that relied
 * on its own `error` code for the frontend to distinguish 403 reasons —
 * including the mandatory password change flow (Part 73/74).
 */
import { ForbiddenException, HttpException, HttpStatus, BadRequestException } from '@nestjs/common';

/**
 * find-e0163405: reportToSentry() read (request as any).tenantId /
 * (request as any).userId -- properties that never existed. TenantGuard
 * sets request.tenant.id, AuthGuard sets request.auth.userId. This test
 * mocks the Sentry module directly (real Sentry is disabled with no DSN
 * in the test env, which would otherwise make reportToSentry's whole body
 * an early-return no-op) to prove the tags now actually get set from the
 * real, nested request shape.
 */
const mockSetTag = jest.fn();
const mockSetUser = jest.fn();
const mockCaptureException = jest.fn();
jest.mock('../../instrument', () => ({
  Sentry: {
    withScope: (fn: (scope: { setTag: jest.Mock; setUser: jest.Mock }) => void) =>
      fn({ setTag: mockSetTag, setUser: mockSetUser }),
    captureException: mockCaptureException,
  },
}));

import { GlobalExceptionFilter } from './global-exception.filter';

function buildHost(request: Record<string, unknown> = {}) {
  const json = jest.fn();
  const header = jest.fn().mockReturnThis();
  const status = jest.fn().mockReturnValue({ header, json });
  const response = { status, header, json };
  const host = {
    switchToHttp: () => ({
      getResponse: () => response,
      getRequest: () => ({ method: 'GET', url: '/api/v1/artists', headers: {}, ...request }),
    }),
  };
  return { host: host as any, status, json };
}

describe('GlobalExceptionFilter — Sentry tagging (find-e0163405)', () => {
  beforeEach(() => jest.clearAllMocks());

  it('tags tenantId from request.tenant.id and sets the Sentry user from request.auth.userId', () => {
    const filter = new GlobalExceptionFilter();
    const { host } = buildHost({ tenant: { id: 'tenant-a' }, auth: { userId: 'user-a' } });

    filter.catch(new Error('boom -- unhandled'), host);

    expect(mockSetTag).toHaveBeenCalledWith('tenantId', 'tenant-a');
    expect(mockSetUser).toHaveBeenCalledWith({ id: 'user-a' });
    expect(mockCaptureException).toHaveBeenCalled();
  });

  it('does not set tenantId/user tags when the request has no tenant/auth context', () => {
    const filter = new GlobalExceptionFilter();
    const { host } = buildHost();

    filter.catch(new Error('boom -- unhandled, no context'), host);

    expect(mockSetTag).not.toHaveBeenCalledWith('tenantId', expect.anything());
    expect(mockSetUser).not.toHaveBeenCalled();
  });
});

describe('GlobalExceptionFilter', () => {
  it('preserves the custom `error` code from the exception payload (e.g. MUST_CHANGE_PASSWORD)', () => {
    const filter = new GlobalExceptionFilter();
    const { host, status, json } = buildHost();

    filter.catch(
      new ForbiddenException({ error: 'MUST_CHANGE_PASSWORD', message: 'Troca de senha obrigatória.' }),
      host,
    );

    expect(status).toHaveBeenCalledWith(HttpStatus.FORBIDDEN);
    expect(json).toHaveBeenCalledWith(expect.objectContaining({
      error: 'MUST_CHANGE_PASSWORD',
      message: 'Troca de senha obrigatória.',
    }));
  });

  it('preserves other custom codes (e.g. TENANT_SUSPENDED)', () => {
    const filter = new GlobalExceptionFilter();
    const { host, json } = buildHost();

    filter.catch(new ForbiddenException({ error: 'TENANT_SUSPENDED', message: 'Tenant suspenso.' }), host);

    expect(json).toHaveBeenCalledWith(expect.objectContaining({ error: 'TENANT_SUSPENDED' }));
  });

  it('preserves the standard HTTP reason-phrase already generated by Nest built-ins (e.g. "Bad Request")', () => {
    const filter = new GlobalExceptionFilter();
    const { host, json } = buildHost();

    filter.catch(new BadRequestException('payload inválido'), host);

    expect(json).toHaveBeenCalledWith(expect.objectContaining({
      error: 'Bad Request',
      message: 'payload inválido',
    }));
  });

  it('uses the class name when the exception is generic (HttpException with a string)', () => {
    const filter = new GlobalExceptionFilter();
    const { host, json } = buildHost();

    filter.catch(new HttpException('erro genérico', HttpStatus.NOT_FOUND), host);

    expect(json).toHaveBeenCalledWith(expect.objectContaining({
      error: 'HttpException',
      message: 'erro genérico',
    }));
  });
});
