/**
 * packages/ai-skills/src/postiz/contracts.ts
 *
 * Contracts of the postiz skill (version 1.0.0).
 * PUBLISH READINESS assessment of a content post (`marketing_content_posts`,
 * already generated by social-content) — it NEVER publishes, schedules or runs
 * anything on a real provider.
 *
 * About the name "postiz": there is zero reference to the "Postiz" vendor in
 * the product (repo-wide grep, zero hits), and an earlier mission investigation
 * explicitly recorded that no vendor decision was authorized
 * (CANDIDATE_SOCIAL_PUBLISHING_GATEWAY only). This skill does NOT pick the
 * vendor — it implements the publish-readiness BOUNDARY in a provider-agnostic
 * way, reusing:
 *   - IntegrationBaseService.getOAuthStatus(tenantId, userId, provider) — the
 *     existing real OAuth connection state for instagram/tiktok/youtube;
 *   - the absence of any integration service for facebook/twitter/threads
 *     (reported as NOT_IMPLEMENTED, never fabricated);
 *   - `MarketingPublishingProcessor.publish()` itself, which is already a
 *     self-documented stub ("Publicação real para {channel} não configurada")
 *     for EVERY channel — this skill NEVER implies otherwise.
 *
 * Mandatory invariants (never violated by this skill):
 *   GENERATED != APPROVED != SCHEDULED != PUBLISHED != SUCCESSFULLY_MEASURED
 */

import type { SkillLanguage, SkillPriority } from "../shared/primitives";

export type PostizLanguage = SkillLanguage;

/** Reuses ExternalProviderStatus (@music-os-360/types) + NOT_IMPLEMENTED for
 * channels without any integration service in the code. */
export type PostizChannelReadiness =
  | "dependency_not_met"
  | "available_not_connected"
  | "connected"
  | "requires_reauth"
  | "provider_error"
  | "not_implemented";

export interface PostizChannelState {
  channel: string;
  readiness: PostizChannelReadiness;
}

// ─── Input ────────────────────────────────────────────────────────────────────

export interface PostizInput {
  postTitle: string;
  channel: string;
  channelReadiness: PostizChannelReadiness;
  hasCopy: boolean;
  copyLength: number;
  context?: string;
  language?: PostizLanguage;
}

// ─── Output blocks ────────────────────────────────────────────────────────────

export interface PostizBlocker {
  blocker: string;
  action: string;
}

export interface PostizRecommendedAction {
  action: string;
  priority: SkillPriority;
}

// ─── Output ───────────────────────────────────────────────────────────────────

export interface PostizOutput {
  readinessSummary: string;
  readyToRequestPublish: boolean;
  blockers: PostizBlocker[];
  recommendedActions: PostizRecommendedAction[];
}
