#!/usr/bin/env node
// Writes .claude/docs/pack/evidence-index.md: every evidence record of the active mission plus the
// current result of each gate. Freshness is decided by gate-engine (path-scoped criteria), not here.
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { workspaceFingerprint } from "./lib/hash.mjs";

const root = process.cwd();
const state = JSON.parse(fs.readFileSync(path.join(root, ".claude/ops/state.json"), "utf8"));
const fp = workspaceFingerprint(root);
const esc = (t) => String(t ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ").slice(0, 170);

const criterionOf = new Map();
for (const r of state.requirements ?? []) for (const c of r.acceptanceCriteria ?? []) for (const id of c.evidenceIds ?? []) criterionOf.set(id, c.id);

const rows = [];
for (const id of state.evidenceIds ?? []) {
  const file = path.join(root, ".claude/ops/evidence", `${id}.json`);
  if (fs.existsSync(file)) rows.push(JSON.parse(fs.readFileSync(file, "utf8")));
}
rows.sort((a, b) => String(b.createdAt).localeCompare(String(a.createdAt)));

const gates = ["completion", "security", "pack-integrity", "human-approval", "operational-automation"].map((g) => {
  const r = spawnSync("node", [".claude/runtime/gate-engine.mjs", g], { cwd: root, encoding: "utf8" });
  let status = "ERROR";
  try { status = JSON.parse(r.stdout).status; } catch { /* leave ERROR */ }
  return { gate: g, status };
});

let md = `# Evidence index\n\nGenerated by \`.claude/runtime/evidence-index.mjs\` for mission \`${state.missionId}\`.\n\n- HEAD: \`${fp.head}\`\n- Workspace fingerprint: \`${fp.fingerprint}\`\n- Evidence records of the mission: ${rows.length}\n\n## Gates\n\n| Gate | Result |\n|---|---|\n`;
for (const g of gates) md += `| ${g.gate} | ${g.status} |\n`;
md += `\n## Evidence records (newest first)\n\n| Id | Type | Criterion | Command / reviewer | Result | Status | Created |\n|---|---|---|---|---|---|---|\n`;
for (const e of rows) {
  md += `| \`${e.id}\` | ${e.type} | ${criterionOf.get(e.id) ?? "-"} | ${esc(e.command ?? e.reviewer)} | ${e.type === "COMMAND" ? `exit ${e.exitCode}` : e.verdict} | ${e.status} | ${e.createdAt} |\n`;
}
const out = path.join(root, ".claude/docs/pack/evidence-index.md");
fs.writeFileSync(out, md);
console.log(JSON.stringify({ status: "OK", file: path.relative(root, out), records: rows.length, gates }));
